# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(350, 291)
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 281, 261))
        self.groupBox.setObjectName("groupBox")
        self.edt_luong = QtWidgets.QLineEdit(self.groupBox)
        self.edt_luong.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.edt_luong.setText("")
        self.edt_luong.setObjectName("edt_luong")
        self.edt_ngaySinh = QtWidgets.QDateEdit(self.groupBox)
        self.edt_ngaySinh.setGeometry(QtCore.QRect(150, 140, 110, 22))
        self.edt_ngaySinh.setDateTime(QtCore.QDateTime(QtCore.QDate(2001, 1, 1), QtCore.QTime(0, 0, 0)))
        self.edt_ngaySinh.setCalendarPopup(True)
        self.edt_ngaySinh.setObjectName("edt_ngaySinh")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(150, 120, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 70, 91, 16))
        self.label_2.setObjectName("label_2")
        self.edt_hoTen = QtWidgets.QLineEdit(self.groupBox)
        self.edt_hoTen.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.edt_hoTen.setText("")
        self.edt_hoTen.setObjectName("edt_hoTen")
        self.hoTen1 = QtWidgets.QLabel(self.groupBox)
        self.hoTen1.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.hoTen1.setObjectName("hoTen1")
        self.edt_gioiTinh = QtWidgets.QComboBox(self.groupBox)
        self.edt_gioiTinh.setGeometry(QtCore.QRect(10, 140, 69, 22))
        self.edt_gioiTinh.setObjectName("edt_gioiTinh")
        self.edt_gioiTinh.addItem("")
        self.edt_gioiTinh.addItem("")
        self.hoTen1_2 = QtWidgets.QLabel(self.groupBox)
        self.hoTen1_2.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.hoTen1_2.setObjectName("hoTen1_2")
        self.edt_diaChi = QtWidgets.QLineEdit(self.groupBox)
        self.edt_diaChi.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.edt_diaChi.setText("")
        self.edt_diaChi.setObjectName("edt_diaChi")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 170, 47, 13))
        self.label.setObjectName("label")
        self.edt_maPB = QtWidgets.QLineEdit(self.groupBox)
        self.edt_maPB.setGeometry(QtCore.QRect(150, 190, 113, 20))
        self.edt_maPB.setText("")
        self.edt_maPB.setObjectName("edt_maPB")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(150, 170, 81, 16))
        self.label_4.setObjectName("label_4")
        self.saveTT = QtWidgets.QPushButton(self.groupBox)
        self.saveTT.setGeometry(QtCore.QRect(180, 220, 75, 23))
        self.saveTT.setObjectName("saveTT")
        self.edt_maNV = QtWidgets.QLineEdit(self.groupBox)
        self.edt_maNV.setEnabled(True)
        self.edt_maNV.setGeometry(QtCore.QRect(80, 20, 141, 31))
        self.edt_maNV.setStyleSheet("background-color: rgb(88, 88, 88);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.edt_maNV.setReadOnly(False)
        self.edt_maNV.setObjectName("edt_maNV")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(40, 30, 47, 13))
        self.label_5.setObjectName("label_5")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "Chỉnh sửa thông tin"))
        self.groupBox.setTitle(_translate("MainWindow2", "Thông tin nhân viên"))
        self.label_3.setText(_translate("MainWindow2", "Ngay Sinh"))
        self.label_2.setText(_translate("MainWindow2", "Luong"))
        self.hoTen1.setText(_translate("MainWindow2", "Ho Ten Nhan Vien"))
        self.edt_gioiTinh.setItemText(0, _translate("MainWindow2", "Nam"))
        self.edt_gioiTinh.setItemText(1, _translate("MainWindow2", "Nữ"))
        self.hoTen1_2.setText(_translate("MainWindow2", "Gioi Tinh"))
        self.label.setText(_translate("MainWindow2", "Dia Chi"))
        self.label_4.setText(_translate("MainWindow2", "Ma Phong Ban"))
        self.saveTT.setText(_translate("MainWindow2", "Save"))
        self.edt_maNV.setText(_translate("MainWindow2", "Nhập MÃ  NV  "))
        self.label_5.setText(_translate("MainWindow2", "Ma NV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec_())
